A_btn_signin = '//button[@id="signin"]'
A_txtbox_email = '//input[@id="email"]'
A_txtbox_password = '//input[@name="password"]'
A_btn_login = '//button[normalize-space()="Sign In"]'
A_Error_login = '//p[contains(text(), "Please enter the correct login details")]'
A_Sidebar = '//nav[@class="sidebar popup false false"]'
A_link_hire = '//a[@href="/hiring/jobs"]'
A_jobcard = '//div[@class="AvailableJobs_jobContainer__PXTFM"]'
A_ind_jobcard ='//div[@class="JobCard_mainContainer__a++gW"]'
A_job_select = "//body/div[@id='root']/div/main[@class='app_app__WWy0F']/div[@class='JobBoard_ancestorContainer__SjnY7']/div[@id='mui-p-60007-P-Available Jobs']/div/div[@class='AvailableJobs_mainContainer__ZYRVO']/div[@class='AvailableJobs_jobContainer__PXTFM']/div[2]"
A_btn_job_apply = '//button[@class="JobInfo_applyBtn__tBOwj"]'
A_btn_job_applied = '//button[text()="Applied Jobs"]'
A_input_work_experience = '//p[contains(text(), "work experience")]/following-sibling::input[@type="number"]'
A_input_notice_period = '//p[contains(text(), "notice period")]/following-sibling::input[@type="number"]'
A_ctc_option = '//select[@class="Questionnair_select__Xmjid"]'
A_select_ctc = '//option[@value="10-15 LPA"]'
A_wfh_hybrid = '//input[@value="No" and @name="Willing to work from office/hybrid?"]'
A_relocate = '//input[@value="Yes" and @name="Willing to relocate?"]'
A_btn_submit = '//button[contains(text(),"Submit")]'
A_btn_cancel = '//button[contains(text(),"Cancel")]'
A_btn_back_jobboard = '//button[@id="backToJobBoard"]'
A_btn_clear_login_error = '//button[@class="cursor-pointer font-sans button-border-radius btn-close-notification relative inline-block p-0 w-4 h-4"]'
A_btn_view_profile = '//button[@id="resumeButton"]'
A_btn_edit_profile = '//button[@id="backButton"]'
A_drop_file =  '//input[@type="file"]'
A_btn_update = '//button[normalize-space()="Update"]'
A_applied_jobcard = "//body/div[@id='root']/div/main[@class='app_app__WWy0F']/div[@class='JobBoard_ancestorContainer__SjnY7']/div[@id='mui-p-93702-P-Applied Jobs']/div[@class='AppliedJobs_mainContainer__4I0fc']/div[@class='AvailableJobs_jobContainer__PXTFM']/div[1]"
A_signout = '//span[normalize-space()="Sign Out"]'
A_input_fname = '//input[@id="first-name"]'
A_input_lname = '//input[@id="last-name"]'
A_input_number = '//input[@id="number"]'
A_input_email ='//input[@id="email"]'
A_dropdown_state = '//input[@id="state-select"]'
A_input_loc = '//input[@id="location"]'
A_input_dob = '//input[@id="dob"]'
A_btn_next = '//button[contains(text(),"Next") and @id="nextButton"]'
A_btn_Finish = '//button[contains(text(),"Finish") and @id="nextButton"]'
A_input_school = '//input[@id="high-school-name"]'
A_txtbox_strength = '//textarea[@id="strengths"]'
A_btn_confirm = '//button[contains(text(), "Confirm") and @id="confirmbutton"]'